/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sr5CampaignManager.dialogs;

import sr5CampaignManager.models.SpinnerFloatModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import sr5CampaignManager.models.LineWidthComboBoxModel;
import sr5CampaignManager.models.MyComboBoxCellRenderer;
import sr5CampaignManager.models.NamedColourComboBoxModel;
import sr5CampaignManager.objects.Map;
import sr5CampaignManager.objects.maps.MapOval;
import sr5CampaignManager.objects.maps.NamedColour;
import sr5CampaignManager.events.MapChangeEvent;

/**
 *
 * @author nbp184
 */
public class MapOvalPanel extends MapDrawingObjectPanel<MapOval> {

    private MapOval mapOval;
    
    /**
     * Creates new form MapOvalPanel
     */
    public MapOvalPanel(Map map) {
        initComponents();
        mapOval = null;
        cbColour.setModel(new NamedColourComboBoxModel(map));
        cbColour.setRenderer(new MyComboBoxCellRenderer(MyComboBoxCellRenderer.NAMED_COLOUR));
        
        cbLineWidth.setModel(new LineWidthComboBoxModel());
        cbLineWidth.setRenderer(new MyComboBoxCellRenderer(MyComboBoxCellRenderer.LINE_WIDTH));
        cbLineWidth.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED) {
                    cbLineWidthItemSelected();
                }
            }
        });
        
        spnX1.setModel(new SpinnerFloatModel(0f, 0f, map.width*1f, 0.5f));
        spnY1.setModel(new SpinnerFloatModel(0f, 0f, map.height*1f, 0.5f));
        spnX2.setModel(new SpinnerFloatModel(0f, 0f, null, 0.5f));
        spnY2.setModel(new SpinnerFloatModel(0f, 0f, null, 0.5f));
        
        btnRemove.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cbColour = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbLineWidth = new javax.swing.JComboBox();
        cbFilled = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        spnX1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnY1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnX2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spnY2 = new javax.swing.JSpinner();
        btnAddUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        spnLayer = new javax.swing.JSpinner();

        jLabel5.setText("Colour");

        cbColour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Line Width");

        cbLineWidth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFilled.setText("Filled");

        jLabel1.setText("Centre X");

        jLabel2.setText("Y");

        jLabel3.setText("Radius X");

        jLabel4.setText("Y");

        btnAddUpdate.setText("Add");
        btnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpdateActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel7.setText("Layer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnY2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLineWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbFilled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbLineWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(spnLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbFilled))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spnY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUpdate)
                    .addComponent(btnRemove)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUpdateActionPerformed
        if(mapOval != null) {
            mapOval.colour = (NamedColour)cbColour.getSelectedItem();
            mapOval.lineWidth = ((LineWidthComboBoxModel)cbLineWidth.getModel()).getValue();
            mapOval.centre[0] = (Float)spnX1.getValue();
            mapOval.centre[1] = (Float)spnY1.getValue();
            mapOval.radius[0] = (Float)spnX2.getValue();
            mapOval.radius[1] = (Float)spnY2.getValue();
            mapOval.filled = cbFilled.isSelected();
            mapOval.layer = (Integer)spnLayer.getValue();
            fireMapChange(new MapChangeEvent(MapChangeEvent.UPDATE, mapOval));
        } else {
            mapOval = new MapOval((Float)spnX1.getValue(), (Float)spnY1.getValue(), (Float)spnX2.getValue(), (Float)spnY2.getValue(), cbFilled.isSelected());
            mapOval.colour = (NamedColour)cbColour.getSelectedItem();
            mapOval.lineWidth = ((LineWidthComboBoxModel)cbLineWidth.getModel()).getValue();
            mapOval.layer = (Integer)spnLayer.getValue();
            fireMapChange(new MapChangeEvent(MapChangeEvent.ADD, mapOval));
        }
    }//GEN-LAST:event_btnAddUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(mapOval != null) {
            fireMapChange(new MapChangeEvent(MapChangeEvent.REMOVE, mapOval));
        } else {
            JOptionPane.showMessageDialog(this, "Must select oval", "Removing", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        fireMapChange(new MapChangeEvent(MapChangeEvent.CANCEL, mapOval));
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUpdate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cbColour;
    private javax.swing.JCheckBox cbFilled;
    private javax.swing.JComboBox cbLineWidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner spnLayer;
    private javax.swing.JSpinner spnX1;
    private javax.swing.JSpinner spnX2;
    private javax.swing.JSpinner spnY1;
    private javax.swing.JSpinner spnY2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setObject(MapOval object) {
        mapOval = object;
        btnAddUpdate.setText("Update");
        btnRemove.setVisible(true);
        cbColour.setSelectedItem(mapOval.colour);
        boolean found = false;
        for(int i = 0; i < LineWidthComboBoxModel.values.length; i++) {
            if(mapOval.lineWidth == LineWidthComboBoxModel.values[i]) {
                cbLineWidth.setSelectedIndex(i);
                found = true;
                break;
            }
        }
        if(!found) {
            ((LineWidthComboBoxModel)cbLineWidth.getModel()).setValue(mapOval.lineWidth);
            cbLineWidth.setSelectedIndex(LineWidthComboBoxModel.values.length);
        }
        spnX1.setValue(mapOval.centre[0]);
        spnY1.setValue(mapOval.centre[1]);
        spnX2.setValue(mapOval.radius[0]);
        spnY2.setValue(mapOval.radius[1]);
        cbFilled.setSelected(mapOval.filled);
        spnLayer.setValue(mapOval.layer);
        setBackground(highlight);
    }

    @Override
    public void clearData() {
        mapOval = null;
        btnAddUpdate.setText("Add");
        btnRemove.setVisible(false);
        cbColour.setSelectedIndex(0);
        cbLineWidth.setSelectedIndex(LineWidthComboBoxModel.defaultIndex);
        spnX1.setValue(0);
        spnY1.setValue(0);
        spnX2.setValue(0);
        spnY2.setValue(0);
        cbFilled.setSelected(false);
        spnLayer.setValue(0);
        setBackground(plain);
    }
    
    private void cbLineWidthItemSelected() {
        LineWidthComboBoxModel model = (LineWidthComboBoxModel)cbLineWidth.getModel();
        if(model.isCustomSelected()) {
            NumberSelectorDialog nsd = new NumberSelectorDialog(null, "Custom Line Width..", model.getValue(), false);
            if(nsd.showDialog() == NumberSelectorDialog.OK) {
                model.setValue(nsd.getNumber());
            }
        }
    }

    @Override
    public boolean isOfType(String typeName) {
        return typeName.compareTo("MapOval") == 0;
    }
}
