/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sr5CampaignManager.dialogs;

import javax.swing.JOptionPane;
import sr5CampaignManager.models.MyComboBoxCellRenderer;
import sr5CampaignManager.models.NamedColourComboBoxModel;
import sr5CampaignManager.objects.Map;
import sr5CampaignManager.objects.maps.MapText;
import sr5CampaignManager.objects.maps.NamedColour;
import sr5CampaignManager.events.MapChangeEvent;

/**
 *
 * @author nbp184
 */
public class MapTextPanel extends MapDrawingObjectPanel<MapText> {

    private MapText mapText;
    
    /**
     * Creates new form MapTextPanel
     */
    public MapTextPanel(Map map) {
        initComponents();
        cbColour.setModel(new NamedColourComboBoxModel(map));
        cbColour.setRenderer(new MyComboBoxCellRenderer(MyComboBoxCellRenderer.NAMED_COLOUR));
        
        spnFontSize.setValue(12);
        
        btnRemove.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spnFontSize = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cbColour = new javax.swing.JComboBox();
        cbRotated = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        spnX1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnY1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        cbHorizontal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbVertical = new javax.swing.JComboBox();
        btnAddUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spnLayer = new javax.swing.JSpinner();

        jLabel4.setText("Text");

        jLabel6.setText("Font Size");

        jLabel5.setText("Colour");

        cbColour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbRotated.setText("Rotated");

        jLabel1.setText("X");

        jLabel2.setText("Y");

        jLabel7.setText("Horizontal Orientation");

        cbHorizontal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Left", "Centre", "Right" }));

        jLabel3.setText("Vertical Orientation");

        cbVertical.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Middle", "Baseline" }));
        cbVertical.setSelectedIndex(2);

        btnAddUpdate.setText("Add");
        btnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpdateActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("Layer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtText))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRotated))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spnLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRotated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUpdate)
                    .addComponent(btnRemove)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUpdateActionPerformed
        if(mapText != null) {
            mapText.colour = (NamedColour)cbColour.getSelectedItem();
            mapText.fontSize = -1;
            mapText.point[0] = (Integer)spnX1.getValue();
            mapText.point[1] = (Integer)spnY1.getValue();
            mapText.orientation[0] = cbHorizontal.getSelectedIndex();
            mapText.orientation[1] = cbVertical.getSelectedIndex();
            mapText.rotate = cbRotated.isSelected();
            mapText.text = txtText.getText();
            mapText.fontSize = (Integer)spnFontSize.getValue();
            mapText.layer = (Integer)spnLayer.getValue();
            fireMapChange(new MapChangeEvent(MapChangeEvent.UPDATE, mapText));
        } else {
            mapText = new MapText(txtText.getText(), (Integer)spnFontSize.getValue(), (Integer)spnX1.getValue(), (Integer)spnY1.getValue(), cbHorizontal.getSelectedIndex(), cbVertical.getSelectedIndex(), cbRotated.isSelected());
            mapText.colour = (NamedColour)cbColour.getSelectedItem();
            mapText.layer = (Integer)spnLayer.getValue();
            fireMapChange(new MapChangeEvent(MapChangeEvent.ADD, mapText));
        }
    }//GEN-LAST:event_btnAddUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(mapText != null) {
            fireMapChange(new MapChangeEvent(MapChangeEvent.REMOVE, mapText));
        } else {
            JOptionPane.showMessageDialog(this, "Must select text", "Removing", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        fireMapChange(new MapChangeEvent(MapChangeEvent.CANCEL, mapText));
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUpdate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cbColour;
    private javax.swing.JComboBox cbHorizontal;
    private javax.swing.JCheckBox cbRotated;
    private javax.swing.JComboBox cbVertical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner spnFontSize;
    private javax.swing.JSpinner spnLayer;
    private javax.swing.JSpinner spnX1;
    private javax.swing.JSpinner spnY1;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setObject(MapText object) {
        mapText = object;
        btnAddUpdate.setText("Update");
        btnRemove.setVisible(true);
        txtText.setText(mapText.text);
        cbColour.setSelectedItem(mapText.colour);
        spnX1.setValue(mapText.point[0]);
        spnY1.setValue(mapText.point[1]);
        cbHorizontal.setSelectedIndex(mapText.orientation[0]);
        cbVertical.setSelectedIndex(mapText.orientation[1]);
        cbRotated.setSelected(mapText.rotate);
        spnFontSize.setValue(mapText.fontSize);
        spnLayer.setValue(mapText.layer);
        setBackground(highlight);
    }

    @Override
    public void clearData() {
        mapText = null;
        btnAddUpdate.setText("Add");
        btnRemove.setVisible(false);
        cbColour.setSelectedIndex(0);
        spnX1.setValue(0);
        spnY1.setValue(0);
        cbHorizontal.setSelectedIndex(0);
        cbVertical.setSelectedIndex(2);
        spnFontSize.setValue(12);
        cbRotated.setSelected(false);
        txtText.setText("");
        spnLayer.setValue(0);
        setBackground(plain);
    }

    @Override
    public boolean isOfType(String typeName) {
        return typeName.compareTo("MapText") == 0;
    }
}
