/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sr5CampaignManager.dialogs;

import sr5CampaignManager.objects.Weapon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;
import sr5CampaignManager.Resources;

/**
 *
 * @author nbp184
 */
public class WeaponSelectDialog extends javax.swing.JDialog {
    
    private static final String[] buttonNames = {"Try Again", "Cancel"};
    
    private Resources r;
    private boolean ok;
    private WeapTreeNode selected;
    
    /**
     * Creates new form WeaponSelectDialog
     */
    public WeaponSelectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ok = false;
        selected = null;
        
        rbRanged.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnGrpRangedMeleeActionPerformed(e);
            }
        });
        rbMelee.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnGrpRangedMeleeActionPerformed(e);
            }
        });
        
        r = Resources.get();
       
        rbRanged.doClick();
    }
    
    public WeaponSelectDialog(javax.swing.JPanel parent, boolean modal) {
        super((java.awt.Frame)null, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.pack();
        rbRanged.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnGrpRangedMeleeActionPerformed(e);
            }
        });
        rbMelee.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnGrpRangedMeleeActionPerformed(e);
            }
        });
        
        r = Resources.get();
       
        rbRanged.doClick();
        ok = false;
        selected = null;
    }
    
    public boolean weaponSelected() {
        return ok;
    }
    
    public Weapon getSelectedWeapon() {
        return selected.getWeapon();
    }
    
    private void btnGrpRangedMeleeActionPerformed(ActionEvent e) {
        DefaultTreeModel model;
        if(rbRanged.isSelected()) {
            model = new DefaultTreeModel(r.getRangedWeapons());
        } else {
            model = new DefaultTreeModel(r.getMeleeWeapons());
        }
        treWeapons.setModel(model);
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpRangedMelee = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rbRanged = new javax.swing.JRadioButton();
        rbMelee = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treWeapons = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Weapon");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnGrpRangedMelee.add(rbRanged);
        rbRanged.setText("Ranged");

        btnGrpRangedMelee.add(rbMelee);
        rbMelee.setText("Melee");

        jScrollPane1.setViewportView(treWeapons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbRanged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMelee))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRanged)
                    .addComponent(rbMelee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        selected = (WeapTreeNode)treWeapons.getSelectionPath().getLastPathComponent();
        if(!selected.isLeaf()) {
            int result = JOptionPane.showOptionDialog(this, "You cannot add an weapon category.", "Error Adding Weapon", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null, buttonNames, buttonNames[0]);
            if(result == JOptionPane.NO_OPTION) {
                this.setVisible(false);
            }
        } else {
            ok = true;
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrpRangedMelee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbMelee;
    private javax.swing.JRadioButton rbRanged;
    private javax.swing.JTree treWeapons;
    // End of variables declaration//GEN-END:variables
}
